import {
  attribute,
  autoGeneratedHashKey,
  table
} from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty } from 'class-validator';

@table('users')
export default class User {
  @autoGeneratedHashKey()
  public userId!: string;

  @IsNotEmpty()
  @attribute()
  public createdAt!: number;

  @IsNotEmpty()
  @attribute()
  public deleted!: boolean;

  @IsNotEmpty()
  @attribute()
  public name!: string;

  @attribute()
  public age?: number;

  constructor() {
    this.createdAt = new Date().getTime();
    this.deleted = false;
  }
}
