version: '2'
services:
  nginx:
    image: nginx:1-alpine
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ./nginx/common:/usr/share/nginx/html/common
    ports:
     - "3000:3000"

  olamundo:
    build: ./olamundo
    ports:
     - "3001:3001"
    volumes:
     - ./olamundo:/code

  ola:
    build: ./ola
    ports:
     - "3002:3002"
    volumes:
     - ./ola:/code

  mundo:
    build: ./mundo
    ports:
     - "3003:3003"
    volumes:
     - ./mundo:/code

  thebasicsapp:
    build: ./the-basics-app
    ports:
     - "3004:3004"
    volumes:
     - ./the-basics-app:/code
