service: cocus-code-challenge

package:
  individually: true

frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment: ${file(./src/env.yml):${self:custom.stage}}

custom:
  stage: ${env:STAGE, opt:stage, self:provider.stage}
  webpack:
    includeModules:
      forceInclude:
        - "@octokit/core"

functions: ${file(./src/serverless-dynamic.js):functions}
  