service:
  name: copafilmes-api

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  cfnRole: arn:aws:iam::741021764664:role/mundodehads-sls-cloudformation
  logRetentionInDays: 7
  region: us-east-1
  versionFunctions: false
  environment: ${file(ymls/environment.yml)}

custom: ${file(ymls/custom.yml)}

resources:
  Resources: ${file(ymls/resources.yml)}

functions: ${file(ymls/functions.yml)}

plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

package:
  exclude:
    - .git/**
    - .gitignore
    - package-lock.json
    - README.md
    - ymls/**
