service: lambda-ddd

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  environment: ${file(./src/env.yml):${self:custom.stage}}

custom:
  stage: ${env:STAGE, opt:stage, self:provider.stage}

package:
  exclude:
    - tests/**

functions: ${file(./src/serverless-dynamic.js):functions}

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}.users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
